version: 2
root-markers:
  - .git
tools:
  eslint_d: &eslint_d
    format-command: "eslint_d --fix-to-stdout --stdin --stdin-filename ${INPUT}"
    format-stdin: true
    lint-command: "eslint_d --f unix --stdin --stdin-filename=${INPUT}"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-after-open: true

  eslint: &eslint
    format-command: "eslint --format unix --fix-to-stdout --stdin --stdin-filename=${INPUT}"
    format-stdin: true
    lint-command: "eslint --format unix --stdin --stdin-filename=${INPUT}"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-after-open: true

  prettierd: &prettierd
    format-command: >
      prettierd ${INPUT} ${--range-start=charStart} ${--range-end=charEnd} \
        ${--tab-width=tabSize}
    format-stdin: true
    lint-after-open: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

languages:
  javascript:
    - <<: *eslint_d
  json:
    - <<: *prettierd
  jsonc:
    - <<: *prettierd
  typescript:
    - <<: *eslint_d
