version: 2
log-level: 5
# Do not use top-level root-markers because they will override the rootMarkers in tools.
tools:
  black: &black
    format-command: "black --fast -"
    format-stdin: true
    lint-command: "black --check --diff -"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-after-open: true

  eslint_d: &eslint_d
    format-command: "eslint_d --fix-to-stdout --stdin --stdin-filename ${INPUT}"
    format-stdin: true
    lint-command: "eslint_d --f unix --stdin --stdin-filename=${INPUT}"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-after-open: true
    rootMarkers: [".git/", "package.json"]

  eslint: &eslint
    format-command: "eslint --format unix --fix-to-stdout --stdin --stdin-filename=${INPUT}"
    format-stdin: true
    lint-command: "eslint --format unix --stdin --stdin-filename=${INPUT}"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-after-open: true
    rootMarkers: [".git/", "package.json"]

  gofmt: &gofmt
    format-command: "gofmt"
    format-stdin: true

  goimports: &goimports
    format-command: "goimports"
    format-stdin: true

  golangci_lint: &golangci_lint
    lint-command: "golangci-lint run --out-format=line-number"
    lint-stdin: false
    lint-formats:
      - "%f:%l:%c: %m"

  basedpyright_wrapped: &basedpyright_wrapped
    lint-command: "~/.vim/efm-stdin-file-wrapper.sh basedpyright --outputjson $tempfile"
    lint-stdin: true
    lint-jq: '.generalDiagnostics[] | {file, message, severity, range, rule}'
    #passthrough:
    #  command: "pyright-langserver"
    #  args: ["--stdio"]

  # mypy_lint is used for static type checking in Python code with mypy.
  # Use for type checking only
  # Does not support linting stdin (need to save file first)
  mypy_lint: &mypy_lint
    lint-command: 'mypy --no-error-summary --show-column-numbers --ignore-missing-imports --disallow-untyped-defs --disallow-incomplete-defs ${INPUT}'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
    lint-after-open: true

  # flake8_lint is used for linting Python code with flake8.
  flake8_lint: &flake8_lint
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    lint-after-open: true
    root-markers:
      - setup.cfg
      - pyproject.toml
      - tox.ini
      - .flake8
      - .git/

  pyright: &pyright
    lint-command: "~/.vim/efm-stdin-file-wrapper.sh pyright --outputjson $tempfile"
    lint-stdin: false
    lint-ignore-exit-code: false
    lint-after-open: true
    lint-jq: '.generalDiagnostics[] | {file, message, severity, range, rule}'
    rootMarkers:
      - .git/
      - requirements.txt

  ruff: &ruff
    lint-command: 'ruff check --force-exclude --output-format=text ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %m'
    lint-ignore-exit-code: true
    format-command: 'ruff format -'
    format-stdin: true

  sql_language_server: &sql_language_server
    command: sql-language-server
    args: ["up", "--method", "stdio"]
    filetypes: [sql]
    rootMarkers: [".git/", "package.json"]
    settings:
      sql:

  #sql-language-server-ksql:
  #  command: sql-language-server
  #  args: ["up", "--method", "stdio"]
  #  filetypes: [ksql]
  #  rootMarkers: [".git/", "package.json"]
  #  settings:
  #    sql:
  #      dialect: "kafka"

  sql_lint: &sql_lint
    lint-command: "sql-lint --format unix --stdin --stdin-filename=${INPUT}"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-after-open: true

  prettierd: &prettierd
    format-command: >
      prettierd ${INPUT} ${--range-start=charStart} ${--range-end=charEnd} \
        ${--tab-width=tabSize}
    format-stdin: true
    lint-after-open: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

  shfmt: &shfmt
    format-command: "shfmt -ci -s -bn"
    format-stdin: true

languages:
  go:
    - <<: *golangci_lint
    - <<: *gofmt
    - <<: *goimports
  javascript:
    - <<: *eslint_d
  json:
    - <<: *prettierd
  jsonc:
    - <<: *prettierd
  #ksql:
    #- <<: *sql-language-server-ksql
    #- <<: *sql-lint
  python:
    - <<: *basedpyright_wrapped
  sh:
    - <<: *shfmt
  sql:
    - <<: *sql_language_server
    - <<: *sql_lint
  typescript:
    - <<: *eslint_d
